people_names = [
    "Alice Adams",
    "Bob Brown",
    "Charlie Chen",
    "David Davis",
    "Eve Evans",
    "Frank Franklin",
    "Grace Garcia",
    "Hank Hernandez",
    "Ivy Ingram",
    "Jack Johnson",
    "Kate King",
    "Liam Lee",
    "Mia Mitchell",
    "Nathan Nguyen",
    "Olivia Ortiz",
    "Paul Phillips",
    "Quincy Quintero",
    "Rose Rodriguez",
    "Sam Smith",
    "Tina Taylor",
    "Uma Upton",
    "Victor Vargas",
    "Wendy Williams",
    "Xander Xavier",
    "Yara Young",
    "Zane Zimmerman"
]

book_reviews = [
    "A captivating tale with rich characters and vivid imagery. Highly recommended!",
    "An intriguing and thought-provoking read that kept me hooked from start to finish.",
    "A beautifully written book that tugs at the heartstrings. A must-read for any book lover.",
    "A thrilling page-turner with unexpected twists and turns. Couldn't put it down!",
    "A powerful and poignant story that left me deeply moved. Beautifully written and expertly crafted.",
    "An enchanting and magical book that swept me away to a different world. A true gem.",
    "A heartwarming story of love, loss, and redemption. Poignant and beautifully written.",
    "An engaging and well-paced novel with a unique and original premise. I was captivated from the first page.",
    "A beautifully written and emotionally resonant tale that will stay with me for a long time.",
    "A gripping and suspenseful read that kept me on the edge of my seat. I couldn't turn the pages fast enough!",
    "A touching and poignant exploration of the human condition. A book that will make you think and feel deeply.",
    "A mesmerizing and lyrical novel that transports readers to a different time and place. I was captivated by the prose.",
    "An epic and sweeping saga that spans generations. A masterful work of historical fiction.",
    "A witty and humorous novel that had me laughing out loud. A delightful and entertaining read.",
    "A haunting and atmospheric story that lingers in the mind long after the last page. A literary masterpiece.",
    "A thrilling and suspenseful mystery with well-drawn characters and a cleverly crafted plot. Highly recommended for fans of the genre.",
    "A heartwarming and uplifting tale of resilience and hope. A celebration of the human spirit.",
    "A thought-provoking and timely novel that tackles important social issues with sensitivity and grace. A must-read for our times.",
    "A beautifully written and evocative book that transports readers to a different era. A must-read for historical fiction enthusiasts."
]

book_status_choices = [
    "Reading",
    "Read",
    "Want To Read"
    ]

genre_names = [
        "Mystery/Thriller",
        "Science Fiction",
        "Fantasy",
        "Romance",
        "Historical Fiction",
        "Horror",
        "Young Adult",
        "Literary Fiction",
        "Crime/Noir",
        "Adventure",
        "Biography/Autobiography",
        "Non-Fiction",
        "Self-Help",
        "Memoir",
        "Poetry",
        "Drama/Play",
        "Comedy/Humor",
        "Western",
        "Dystopian",
        "Children's/Picture Book",
        "Paranormal/Supernatural",
        "Urban Fantasy",
        "Steampunk",
        "Contemporary Fiction",
        "Magical Realism",
        "Thriller/Suspense",
        "Espionage",
        "War/Military Fiction",
        "Women's Fiction",
        "Sports Fiction",
        "Science/Popular Science",
        "True Crime",
        "Cookbook/Culinary",
        "Travel/Adventure",
        "Art/Photography",
        "Religion/Spirituality",
        "Philosophy",
        "Psychology/Psychological Thriller",
        "LGBTQ+ Fiction",
        "Post-Apocalyptic",
        "Alternate History",
        "Cyberpunk",
        "Supernatural Romance",
        "Time Travel",
        "Cozy Mystery",
        "Folklore/Fairy Tales",
        "Graphic Novel/Comic",
        "Western Romance",
        "Short Stories/Anthology",
        "Classic Literature"
    ]

countries = [
    'China', 'India', 'United States', 'Indonesia', 'Pakistan', 'Brazil', 'Nigeria', 'Bangladesh',
    'Russia', 'Mexico', 'Japan', 'Ethiopia', 'Philippines', 'Egypt', 'Vietnam', 'DR Congo',
    'Turkey', 'Iran', 'Germany', 'Thailand', 'United Kingdom', 'France', 'Italy', 'Tanzania',
    'South Africa', 'Myanmar (formerly Burma)', 'Kenya', 'South Korea', 'Colombia', 'Uganda'
]